TEST_QUERIES = [
{"q": "Comment sont classés les établissements dangereux en trois catégories ?", "expected": "Articles.txt (Article 294)"},
{"q": "Quelles sont les missions de l'Institut National de la Météorologie (INM) ?", "expected": "Lois.txt (Loi n° 2009-10)"},
{"q": "Quels sont les tarifs des redevances pour l'approbation de modèles d'instruments ?", "expected": "TermesJuridiques.txt (Décret n° 2001-588)"},
{"q": "Quelle est la définition de la démission dans la Convention des Teintureries ?", "expected": "Articles.txt (Article 58)"},
{"q": "Quelle loi définit les unités de mesure légales en Tunisie ?", "expected": "Lois.txt (Loi n° 99-40)"},
{"q": "Quelles sont les obligations de surveillance pour les détenteurs de balances automatiques ?", "expected": "TermesJuridiques.txt (Obligations des détenteurs)"},
{"q": "Quels sont les domaines de protection visés par l'article 293 ?", "expected": "Articles.txt (Article 293)"},
{"q": "Quelle est la validité temporelle des étiquettes de salubrité des fruits de mer ?", "expected": "Lois.txt (Loi n° 59-56 / Article 21)"},
{"q": "Quelles sont les normes de carrelage pour les usines de conserves alimentaires ?", "expected": "TermesJuridiques.txt (Décret n° 68-228)"},
{"q": "Quelles mentions doivent figurer exclusivement sur un certificat de travail ?", "expected": "Articles.txt (Article 59)"},
{"q": "Quel organisme est chargé de la normalisation et de la propriété industrielle ?", "expected": "Lois.txt (Loi n° 82-66 / INNORPI)"},
{"q": "Quelle est la marque de poinçonnage utilisée pour l'année 2017 ?", "expected": "TermesJuridiques.txt (Arrêté Poinçonnage 2017)"},
{"q": "Quelle est la sanction pour l'occupation sans permission de la voie publique ?", "expected": "Articles.txt (Code Pénal)"},
{"q": "Quels produits sont exemptés de contrôle vétérinaire à l'importation ?", "expected": "Lois.txt (Article 3 / Produits animaux)"},
{"q": "Quel est le taux de TVA appliqué aux redevances de contrôle métrologique ?", "expected": "TermesJuridiques.txt (Arrêté n° 2018-1353)"},
{"q": "L'indemnité de licenciement est-elle distincte de l'indemnité de préavis ?", "expected": "Articles.txt (Thème : Licenciement)"},
{"q": "Quel texte régit le capital minimum requis pour le commerce de distribution ?", "expected": "Lois.txt (Loi n° 69-1)"},
{"q": "Jusqu'à quand peut-on commercialiser les huiles d'olive étiquetées avant 2013 ?", "expected": "TermesJuridiques.txt (Règlement UE 357-2012)"},
{"q": "Qui est responsable de la sécurité des salariés dans un contrat de prestation ?", "expected": "Articles.txt (Thème : Sous-traitance)"},
{"q": "Quelle loi définit le système national de normalisation ?", "expected": "Lois.txt (Loi n° 2009-38)"},
{"q": "Quel est le barème d'emploi pour la culture des bananes sous serres ?", "expected": "TermesJuridiques.txt (Barèmes agricoles)"},
{"q": "Quelles sont les conditions de réembauche d'un travailleur démissionnaire ?", "expected": "Articles.txt (Article 58 / Convention Collective)"},
{"q": "Quel texte fixe les modalités d'élaboration et de diffusion des normes ?", "expected": "TermesJuridiques.txt (Décret n° 83-724)"},
{"q": "Où sont précisées les missions de l'INNORPI ?", "expected": "Lois.txt (Loi n° 82-66)"},
{"q": "Quelle est la sanction pour l'usage d'eau potable pour le lavage de voitures ?", "expected": "TermesJuridiques.txt (Thème : Gestion de l'eau)"},
{"q": "Quelles sont les exigences de conformité pour les équipements de sécurité ?", "expected": "Articles.txt (Normes de sécurité)"},
{"q": "Quel est le tarif horaire pour une expertise ou un étalonnage métrologique ?", "expected": "TermesJuridiques.txt (Décret n° 2001-588 / Expertise)"},
{"q": "Quelle autorité surveille les établissements de troisième catégorie ?", "expected": "Articles.txt (Article 294 / Surveillance administrative)"},
{"q": "Quelles sont les obligations de l'exploitant d'un dépôt d'explosifs ?", "expected": "TermesJuridiques.txt (Sécurité / Matières explosives)"},
{"q": "Quelle loi régit le contrôle sanitaire vétérinaire à l'exportation ?", "expected": "Lois.txt (Contrôle vétérinaire / Article 3)"},
{"q": "Qu'est-ce qu'un établissement de 1ère catégorie ?", "expected": "Articles.txt (Article 294)"},
{"q": "Quelle est la redevance pour un essai d'un instrument de mesure ?", "expected": "TermesJuridiques.txt (Décret n° 2001-588)"},
{"q": "Où est définie la responsabilité sociétale des entreprises ?", "expected": "Lois.txt (Loi RSE)"},
{"q": "Quels sont les critères pour un contrat de prestation autorisé ?", "expected": "Articles.txt (Droit du travail)"},
{"q": "Quel est le poinçon de vérification pour l'année 2019 ?", "expected": "TermesJuridiques.txt (Arrêté 2019)"},
{"q": "Quelle est la définition juridique d'une denrée alimentaire ?", "expected": "TermesJuridiques.txt (Sécurité alimentaire)"},
{"q": "Quelle loi traite de la protection de l'environnement industriel ?", "expected": "Articles.txt (Prévention des risques)"},
{"q": "Quel est le capital minimum pour le secteur de la distribution ?", "expected": "Lois.txt (Loi n° 69-1)"},
{"q": "Où sont consignés les résultats des essais de pesage ?", "expected": "TermesJuridiques.txt (Registres de contrôle)"},
{"q": "Quelle est la durée de validité du certificat de travail ?", "expected": "Articles.txt (Article 59)"},
{"q": "Qui fixe les missions de l'INM ?", "expected": "Lois.txt (Loi n° 2009-10)"},
{"q": "Quelle lettre arabe est utilisée sur le poinçon de 2017 ?", "expected": "TermesJuridiques.txt (Marque 'ط')"},
{"q": "Quelle est la sanction pour un licenciement abusif ?", "expected": "Articles.txt (Indemnités)"},
{"q": "Quelle est la définition d'un produit animal transformé selon la loi ?", "expected": "Lois.txt (Article 3)"},
{"q": "Où sont définies les catégories de normes ?", "expected": "TermesJuridiques.txt (Décret n° 83-724)"},
{"q": "Comment doit être formulée une demande de démission ?", "expected": "Articles.txt (Article 58)"},
{"q": "Quel texte approuve le statut des agents de l'INNORPI ?", "expected": "TermesJuridiques.txt (Décret n° 2009-1504)"},
{"q": "Quels secteurs bénéficient des services de l'INM ?", "expected": "Lois.txt (Aviation, Marine, Agriculture)"},
{"q": "Quelle est la redevance horaire pour les travaux de métrologie ?", "expected": "TermesJuridiques.txt (5 Dinars)"},
{"q": "Quelle est l'exigence pour les murs au-dessus du carrelage en usine ?", "expected": "TermesJuridiques.txt (Enduit lavable)"},
{"q": "Où est mentionné l'éloignement obligatoire des centres urbains ?", "expected": "Articles.txt (1ère catégorie)"},
{"q": "Quel est l'objet de la loi n° 82-66 ?", "expected": "Lois.txt (Normalisation et Qualité)"},
{"q": "Quelle lettre identifie le poinçonnage de 2019 ?", "expected": "TermesJuridiques.txt (Lettre C)"},
{"q": "Qui surveille les établissements de 3ème catégorie ?", "expected": "Articles.txt (Administration)"},
{"q": "Quels bagages sont exemptés de contrôle sanitaire ?", "expected": "Lois.txt (Bagages personnels voyageurs)"},
{"q": "Quel est le barème pour 1000 volailles en aviculture ?", "expected": "TermesJuridiques.txt (36 jours)"},
{"q": "Quelle est la définition d'une volonté non équivoque de démission ?", "expected": "Articles.txt (Article 58)"},
{"q": "Où se font les vérifications périodiques des instruments ?", "expected": "TermesJuridiques.txt (Locaux Agence ou sites)"},
{"q": "Quelle loi encadre le système national de métrologie ?", "expected": "Lois.txt (Loi n° 99-40)"},
{"q": "Quelle est l'indemnité due en cas de inobservation du préavis ?", "expected": "Articles.txt (Licenciement)"},
{"q": "Quelle est la marque de poinçonnage pour 2026 ?", "expected": "TermesJuridiques.txt (Arrêté 2025)"},
{"q": "Quelle est la redevance pour une fraction d'heure de contrôle ?", "expected": "TermesJuridiques.txt (Heure entière)"},
{"q": "Où est défini le carrelage pour les sols d'usines ?", "expected": "TermesJuridiques.txt (Décret n° 68-228)"},
{"q": "Quel texte parle de l'enquête technique pour les normes ?", "expected": "TermesJuridiques.txt (Décret n° 83-724)"},
{"q": "Quelle est la sanction pénale pour entrave à la sécurité routière ?", "expected": "Articles.txt (15 jours prison)"},
{"q": "Quelle loi oblige l'INNORPI à fixer ses missions ?", "expected": "Lois.txt (Loi n° 2009-38)"},
{"q": "Quelle est la température de conservation pour l'huile d'olive ?", "expected": "TermesJuridiques.txt (Règlement UE)"},
{"q": "Qu'est-ce que l'article 293 définit ?", "expected": "Articles.txt (Dangers et Incommodités)"},
{"q": "Quelle est l'autorité technique pour les prestataires externes ?", "expected": "Articles.txt (Employeur direct)"},
{"q": "Quel est le barème par tête pour l'élevage ovin ?", "expected": "TermesJuridiques.txt (5 jours)"},
{"q": "Quelle est la redevance pour l'étalonnage ?", "expected": "TermesJuridiques.txt (10 Dinars/heure)"},
{"q": "Quelle loi régit la pêche et la vente des fruits de mer ?", "expected": "Lois.txt (Loi n° 59-56)"},
{"q": "Où est stockée l'huile d'olive mise en libre pratique ?", "expected": "TermesJuridiques.txt (Règlement 29/2012)"},
{"q": "Qui délivre les étiquettes de salubrité ?", "expected": "Lois.txt (Services vétérinaires)"},
{"q": "Quel est le rôle du comité régional en RSE ?", "expected": "Lois.txt (Avis sur projets)"},
{"q": "Quel document liste les dates d'entrée et de sortie ?", "expected": "Articles.txt (Certificat de travail)"},
{"q": "Quel décret fixe les redevances métrologiques ?", "expected": "TermesJuridiques.txt (Décret 2001-588)"},
{"q": "Quelle est la sanction pour non-présentation du registre de pesage ?", "expected": "TermesJuridiques.txt (Infraction métrologique)"},
{"q": "Quelle loi concerne la sécurité géophysique ?", "expected": "Lois.txt (Loi INM)"},
{"q": "Où est définie la procédure d'homologation des normes ?", "expected": "TermesJuridiques.txt (Décret 83-724)"},
{"q": "Quelle catégorie d'établissement exige des mesures de prévention ?", "expected": "Articles.txt (2ème catégorie)"},
{"q": "Quel texte impose la certification ISO aux promoteurs BTP ?", "expected": "TermesJuridiques.txt (Certification obligatoire)"},
{"q": "Quel est le but de la surveillance administrative de 3ème catégorie ?", "expected": "Articles.txt (Intérêt du voisinage)"},
{"q": "Quelle loi définit la forme juridique des entreprises de distribution ?", "expected": "Lois.txt (Loi 69-1)"},
{"q": "Quel est le tarif horaire pour une fraction d'heure comptée ?", "expected": "TermesJuridiques.txt (5 DT)"},
{"q": "Quelles sont les mentions exclues du certificat de travail ?", "expected": "Articles.txt (Mentions non prévues à l'art 59)"},
{"q": "Où est mentionné l'usage de vignettes pour les balances ?", "expected": "TermesJuridiques.txt (Marques de vérification)"},
{"q": "Quelle loi traite de l'importation d'animaux ?", "expected": "Lois.txt (Article 3)"},
{"q": "Quelle est la sanction pour un emprisonnement de 9 mois ?", "expected": "TermesJuridiques.txt (Usage eau potable)"},
{"q": "Quelle loi définit les missions de l'INNORPI ?", "expected": "Lois.txt (Loi 82-66)"},
{"q": "Quel décret fixe les catégories de normes ?", "expected": "TermesJuridiques.txt (Décret 83-724)"},
{"q": "Quelle est la condition d'éloignement pour la 2ème catégorie ?", "expected": "Articles.txt (Pas rigoureusement nécessaire)"},
{"q": "Où trouve-t-on le capital minimum pour le commerce ?", "expected": "Lois.txt (Décret de secteur)"},
{"q": "Quelle est la marque de poinçonnage pour 2017 (Lettre) ?", "expected": "TermesJuridiques.txt (Lettre U)"},
{"q": "Quel texte parle de l'épuisement des stocks d'huile ?", "expected": "TermesJuridiques.txt (UE 357-2012)"},
{"q": "Quel est le barème pour les bananes (hectares) ?", "expected": "TermesJuridiques.txt (700 jours)"},
{"q": "Quelle est la loi sur le système national de normalisation ?", "expected": "Lois.txt (Loi 2009-38)"},
{"q": "Où est mentionnée la surveillance statistique du remplissage ?", "expected": "TermesJuridiques.txt (Balances automatiques)"},
{"q": "Quelle est la sanction de 60 à 1000 dinars ?", "expected": "TermesJuridiques.txt (Infraction eau)"},
{"q": "Quel texte définit la démission inconditionnelle ?", "expected": "Articles.txt (Article 58)"}
{"q": "Quel est le barème d'emploi pour l'élevage bovin (production de lait) ?", "expected": "TermesJuridiques.txt (Barèmes agricoles)"},
{"q": "Où est mentionnée l'interdiction de mentions discriminatoires sur le certificat de travail ?", "expected": "Articles.txt (Article 59)"},
{"q": "Quel est l'objet de la loi n° 2009-10 relative à l'INM ?", "expected": "Lois.txt (Institut National de la Météorologie)"},
{"q": "Quelle est la procédure d'enquête technique pour l'homologation d'une norme ?", "expected": "TermesJuridiques.txt (Décret n° 83-724)"},
{"q": "Où est définie la 'commodité du voisinage' comme critère de surveillance ?", "expected": "Articles.txt (Article 293)"},
{"q": "Quelle est la redevance horaire pour une expertise métrologique spécifique ?", "expected": "TermesJuridiques.txt (10 Dinars)"},
{"q": "Quelles sont les obligations de l'employeur en cas de réembauche après démission ?", "expected": "Articles.txt (Article 58)"},
{"q": "Quelle loi régit la métrologie légale depuis 1999 ?", "expected": "Lois.txt (Loi n° 99-40)"},
{"q": "Où est précisé le carrelage des murs jusqu'à 1,50 mètre ?", "expected": "TermesJuridiques.txt (Décret n° 68-228)"},
{"q": "Quelle est la lettre arabe sur le poinçon de 2019 ?", "expected": "TermesJuridiques.txt (Lettre ط)"},
{"q": "Quel texte définit la forme juridique obligatoire des entreprises de distribution ?", "expected": "Lois.txt (Loi n° 69-1)"},
{"q": "Où sont classés les établissements ne présentant pas d'inconvénients graves ?", "expected": "Articles.txt (3ème catégorie)"},
{"q": "Quelle est la sanction pour un abonné utilisant l'eau potable pour irriguer ?", "expected": "TermesJuridiques.txt (Gestion de l'eau)"},
{"q": "Qui doit signer la demande de démission du travailleur ?", "expected": "Articles.txt (Le travailleur - Demande écrite)"},
{"q": "Quel est le barème d'emploi pour 1 hectare d'agrumes ?", "expected": "TermesJuridiques.txt (Barèmes agricoles)"},
{"q": "Où est mentionnée l'approbation du statut des agents de l'INNORPI ?", "expected": "TermesJuridiques.txt (Décret n° 2009-1504)"},
{"q": "Quelle est la validité des étiquettes de salubrité pour les coquillages ?", "expected": "Lois.txt (48 heures)"},
{"q": "Qui est chargé de la surveillance administrative des établissements de 3ème catégorie ?", "expected": "Articles.txt (L'administration locale)"},
{"q": "Quel texte modifie le règlement d'exécution 29/2012 sur l'huile d'olive ?", "expected": "TermesJuridiques.txt (Règlement UE 357-2012)"},
{"q": "Quel est le tarif pour une fraction d'heure en contrôle métrologique ?", "expected": "TermesJuridiques.txt (Comptée comme une heure entière)"},
{"q": "Où est définie l'obligation de spécialisation technique pour la sous-traitance ?", "expected": "Articles.txt (Contrat de prestation)"},
{"q": "Quelle loi définit les missions du ministre de l'économie sur la qualité ?", "expected": "Lois.txt (Loi n° 82-66)"},
{"q": "Quelle lettre de l'alphabet latin suit le 'ط' en 2017 ?", "expected": "TermesJuridiques.txt (Lettre U)"},
{"q": "Où est mentionné le registre pour les instruments de remplissage ?", "expected": "TermesJuridiques.txt (Obligations des détenteurs)"},
{"q": "Quelle est la sanction en cas de licenciement sans préavis ?", "expected": "Articles.txt (Indemnité de préavis)"},
{"q": "Qui gère le programme général d'élaboration des normes ?", "expected": "TermesJuridiques.txt (INNORPI / Décret 83-724)"},
{"q": "Où est mentionnée la navigation aérienne dans les services météo ?", "expected": "Lois.txt (Missions de l'INM)"},
{"q": "Quel est le barème pour l'élevage de poulets de chair ?", "expected": "TermesJuridiques.txt (Aviculture)"},
{"q": "Où sont éloignés les établissements de la 1ère catégorie ?", "expected": "Articles.txt (Centres urbains)"},
{"q": "Quel décret fixe les redevances pour l'étalonnage ?", "expected": "TermesJuridiques.txt (Décret n° 2001-588)"},
{"q": "Quelle loi oblige au contrôle vétérinaire des animaux à l'export ?", "expected": "Lois.txt (Article 3)"},
{"q": "Où est défini le contenu exclusif du certificat de travail ?", "expected": "Articles.txt (Article 59)"},
{"q": "Quel texte définit la Responsabilité Sociétale des Entreprises ?", "expected": "Lois.txt (Loi RSE)"},
{"q": "Où est mentionné le poinçonnage de 2026 ?", "expected": "TermesJuridiques.txt (Arrêté 2025)"},
{"q": "Quel est le montant de l'amende minimum pour infraction à l'eau potable ?", "expected": "TermesJuridiques.txt (60 Dinars)"},
{"q": "Qu'est-ce que l'enquête technique pour une norme ?", "expected": "TermesJuridiques.txt (Procédure d'homologation)"},
{"q": "Où est mentionnée l'inconditionnalité de la démission ?", "expected": "Articles.txt (Article 58)"},
{"q": "Quel est le capital minimum requis pour une entreprise de distribution ?", "expected": "Lois.txt (Loi n° 69-1)"},
{"q": "Où est stocké le registre des essais de pesage ?", "expected": "TermesJuridiques.txt (Sur les lieux d'exploitation)"},
{"q": "Quelle loi fixe les missions de l'INM pour le tourisme ?", "expected": "Lois.txt (Loi n° 2009-10)"},
{"q": "Quel est le taux de TVA pour les services de métrologie ?", "expected": "TermesJuridiques.txt (19%)"},
{"q": "Où est définie la deuxième catégorie d'établissements ?", "expected": "Articles.txt (Article 294)"},
{"q": "Quel est le barème pour 1 hectare de vignes ?", "expected": "TermesJuridiques.txt (Barèmes agricoles)"},
{"q": "Qui est responsable de l'hygiène dans une entreprise prestataire ?", "expected": "Articles.txt (L'entreprise bénéficiaire)"},
{"q": "Où est mentionné le statut particulier de l'INNORPI ?", "expected": "TermesJuridiques.txt (Décret n° 2009-1504)"},
{"q": "Quelle loi régit le système national de normalisation ?", "expected": "Lois.txt (Loi n° 2009-38)"},
{"q": "Quel est le tarif pour l'approbation d'un modèle d'instrument ?", "expected": "TermesJuridiques.txt (5 DT / heure)"},
{"q": "Où est définie la notion de danger inhérent à l'exploitation ?", "expected": "Articles.txt (Article 294)"},
{"q": "Quelle est la validité d'une vignette de pesage ?", "expected": "TermesJuridiques.txt (Période de vérification)"},
{"q": "Quelle loi traite du contrôle sanitaire des produits transformés ?", "expected": "Lois.txt (Article 3)"},
{"q": "Où est mentionnée la 'salubrité' comme critère de risque ?", "expected": "Articles.txt (Article 293)"},
{"q": "Quel est le barème pour l'élevage de dindes ?", "expected": "TermesJuridiques.txt (Aviculture)"},
{"q": "Qui effectue les contrôles statistiques de poids ?", "expected": "TermesJuridiques.txt (Le détenteur de l'instrument)"},
{"q": "Quelle loi oblige l'INNORPI à fixer ses fonctions ?", "expected": "Lois.txt (Loi n° 2009-38)"},
{"q": "Où est précisé le revêtement lavable des murs d'usine ?", "expected": "TermesJuridiques.txt (Décret n° 68-228)"},
{"q": "Quelle est la sanction pour un emprisonnement de 6 jours ?", "expected": "TermesJuridiques.txt (Infraction eau)"},
{"q": "Quel texte définit la démission définitive ?", "expected": "Articles.txt (Article 58)"},
{"q": "Où est mentionnée l'étiquette de salubrité pour la pêche ?", "expected": "Lois.txt (Article 21)"},
{"q": "Quel est le barème d'emploi pour la culture sous serres ?", "expected": "TermesJuridiques.txt (700 jours / Ha)"},
{"q": "Où est défini le rôle du ministère de l'Économie sur les normes ?", "expected": "Lois.txt (Loi n° 82-66)"},
{"q": "Quel est le poinçon pour l'année 2017 ?", "expected": "TermesJuridiques.txt (ط + U)"},
{"q": "Qui surveille les manufactures selon l'article 293 ?", "expected": "Articles.txt (Surveillance administrative)"},
{"q": "Où est mentionnée l'exemption pour les petits envois privés ?", "expected": "Lois.txt (Contrôle vétérinaire)"},
{"q": "Quel est le barème pour l'élevage caprin ?", "expected": "TermesJuridiques.txt (Barèmes agricoles)"},
{"q": "Où est définie l'indemnité de licenciement abusive ?", "expected": "Articles.txt (Sociale / Licenciement)"},
{"q": "Quel décret fixe les catégories de normes ?", "expected": "TermesJuridiques.txt (Décret n° 83-724)"},
{"q": "Où est mentionnée la lettre C pour 2019 ?", "expected": "TermesJuridiques.txt (Arrêté métrologie)"},
{"q": "Quelle loi encadre le commerce de distribution ?", "expected": "Lois.txt (Loi n° 69-1)"},
{"q": "Où est mentionné l'éloignement non rigoureusement nécessaire ?", "expected": "Articles.txt (2ème catégorie)"},
{"q": "Quelle est la redevance pour une fraction d'heure de 30 min ?", "expected": "TermesJuridiques.txt (5 DT / Heure entière)"},
{"q": "Qui peut réembaucher un travailleur démissionnaire ?", "expected": "Articles.txt (L'employeur)"},
{"q": "Où sont précisées les missions géophysiques de l'INM ?", "expected": "Lois.txt (Loi n° 2009-10)"},
{"q": "Quel est le barème pour la culture de tomates sous serres ?", "expected": "TermesJuridiques.txt (Barèmes agricoles)"},
{"q": "Où est mentionnée la lettre arabe 'ط' ?", "expected": "TermesJuridiques.txt (Signe de poinçonnage)"},
{"q": "Quel texte définit le certificat de travail au moment du départ ?", "expected": "Articles.txt (Article 59)"},
{"q": "Où est mentionnée la mise en libre pratique de l'huile ?", "expected": "TermesJuridiques.txt (UE 357-2012)"},
{"q": "Quel est le montant de l'amende maximum pour l'eau ?", "expected": "TermesJuridiques.txt (1000 Dinars)"},
{"q": "Où est défini l'intérêt du voisinage pour la 3ème catégorie ?", "expected": "Articles.txt (Article 294)"},
{"q": "Quelle loi traite de la normalisation en Tunisie ?", "expected": "Lois.txt (Loi n° 2009-38)"},
{"q": "Où est mentionné l'usage de vignettes de pesage ?", "expected": "TermesJuridiques.txt (Marques de vérification)"},
{"q": "Quel est le barème pour l'apiculture ?", "expected": "TermesJuridiques.txt (Barèmes agricoles)"},
{"q": "Où est mentionné l'enduit lavable pour les usines ?", "expected": "TermesJuridiques.txt (Décret n° 68-228)"},
{"q": "Quel est le rôle de l'Agence Nationale de Métrologie ?", "expected": "TermesJuridiques.txt (Contrôle et vérification)"},
{"q": "Où est définie la volonté non équivoque ?", "expected": "Articles.txt (Article 58)"},
{"q": "Quelle loi régit la qualité des eaux de consommation ?", "expected": "TermesJuridiques.txt (Directive 98-83-CE)"},
{"q": "Où est mentionnée la marine dans les missions de l'INM ?", "expected": "Lois.txt (Loi n° 2009-10)"},
{"q": "Quel est le barème pour l'élevage de lapins ?", "expected": "TermesJuridiques.txt (Barèmes agricoles)"},
{"q": "Où est mentionnée la lettre U pour 2017 ?", "expected": "TermesJuridiques.txt (Arrêté poinçonnage)"},
{"q": "Quel texte fixe le capital pour chaque secteur commercial ?", "expected": "Lois.txt (Loi n° 69-1)"},
{"q": "Où est mentionnée l'indemnité de préavis ?", "expected": "Articles.txt (Sociale / Licenciement)"},
{"q": "Quel est le tarif horaire pour l'étalonnage ?", "expected": "TermesJuridiques.txt (10 DT)"},
{"q": "Où est définie l'enquête technique pour les normes ?", "expected": "TermesJuridiques.txt (Décret n° 83-724)"},
{"q": "Quelle loi oblige au contrôle sanitaire vétérinaire ?", "expected": "Lois.txt (Article 3)"},
{"q": "Où est mentionnée la troisième catégorie d'établissements ?", "expected": "Articles.txt (Article 294)"},
{"q": "Quel est le barème pour la culture d'oliviers ?", "expected": "TermesJuridiques.txt (Barèmes agricoles)"},
{"q": "Où est défini l'INNORPI ?", "expected": "Lois.txt (Loi n° 82-66)"},
{"q": "Quel est le tarif pour l'approbation d'un modèle ?", "expected": "TermesJuridiques.txt (5 DT / Heure)"},
{"q": "Où est mentionnée la démission écrite ?", "expected": "Articles.txt (Article 58)"},
{"q": "Quel texte modifie le règlement 29/2012 ?", "expected": "TermesJuridiques.txt (UE 357-2012)"},
{"q": "Où sont listées les missions de l'INM ?", "expected": "Lois.txt (Loi n° 2009-10)"}
]