TEST_QUERIES = [
    {"q": "Comment sont classés les établissements dangereux en trois catégories ?", "expected": "data/Articles.txt (Article 294)"},
    {"q": "Quelles sont les missions de l'Institut National de la Météorologie (INM) ?", "expected": "data/Lois.txt (Loi n° 2009-10)"},
    {"q": "Quels sont les tarifs des redevances pour l'approbation de modèles d'instruments ?", "expected": "data/Termesjuridiques.txt (Décret n° 2001-588)"},
    {"q": "Quelle est la définition de la démission dans la Convention des Teintureries ?", "expected": "data/Articles.txt (Article 58)"},
    {"q": "Quelle loi définit les unités de mesure légales en Tunisie ?", "expected": "data/Lois.txt (Loi n° 99-40)"},
    {"q": "Quelles sont les obligations de surveillance pour les détenteurs de balances automatiques ?", "expected": "data/Termesjuridiques.txt (Obligations des détenteurs)"},
    {"q": "Quels sont les domaines de protection visés par l'article 293 ?", "expected": "data/Articles.txt (Article 293)"},
    {"q": "Quelle est la validité temporelle des étiquettes de salubrité des fruits de mer ?", "expected": "data/Lois.txt (Loi n° 59-56 / Article 21)"},
    {"q": "Quelles sont les normes de carrelage pour les usines de conserves alimentaires ?", "expected": "data/Termesjuridiques.txt (Décret n° 68-228)"},
    {"q": "Quelles mentions doivent figurer exclusivement sur un certificat de travail ?", "expected": "data/Articles.txt (Article 59)"},
    {"q": "Quel organisme est chargé de la normalisation et de la propriété industrielle ?", "expected": "data/Lois.txt (Loi n° 82-66 / INNORPI)"},
    {"q": "Quelle est la marque de poinçonnage utilisée pour l'année 2017 ?", "expected": "data/Termesjuridiques.txt (Arrêté Poinçonnage 2017)"},
    {"q": "Quelle est la sanction pour l'occupation sans permission de la voie publique ?", "expected": "data/Articles.txt (Code Pénal)"},
    {"q": "Quels produits sont exemptés de contrôle vétérinaire à l'importation ?", "expected": "data/Lois.txt (Article 3 / Produits animaux)"},
    {"q": "Quel est le taux de TVA appliqué aux redevances de contrôle métrologique ?", "expected": "data/Termesjuridiques.txt (Arrêté n° 2018-1353)"},
    {"q": "L'indemnité de licenciement est-elle distincte de l'indemnité de préavis ?", "expected": "data/Articles.txt (Thème : Licenciement)"},
    {"q": "Quel texte régit le capital minimum requis pour le commerce de distribution ?", "expected": "data/Lois.txt (Loi n° 69-1)"},
    {"q": "Jusqu'à quand peut-on commercialiser les huiles d'olive étiquetées avant 2013 ?", "expected": "data/Termesjuridiques.txt (Règlement UE 357-2012)"},
    {"q": "Qui est responsable de la sécurité des salariés dans un contrat de prestation ?", "expected": "data/Articles.txt (Thème : Sous-traitance)"},
    {"q": "Quelle loi définit le système national de normalisation ?", "expected": "data/Lois.txt (Loi n° 2009-38)"},
    {"q": "Quel est le barème d'emploi pour la culture des bananes sous serres ?", "expected": "data/Termesjuridiques.txt (Barèmes agricoles)"},
    {"q": "Quelles sont les conditions de réembauche d'un travailleur démissionnaire ?", "expected": "data/Articles.txt (Article 58 / Convention Collective)"},
    {"q": "Quel texte fixe les modalités d'élaboration et de diffusion des normes ?", "expected": "data/Termesjuridiques.txt (Décret n° 83-724)"},
    {"q": "Où sont précisées les missions de l'INNORPI ?", "expected": "data/Lois.txt (Loi n° 82-66)"},
    {"q": "Quelle est la sanction pour l'usage d'eau potable pour le lavage de voitures ?", "expected": "data/Termesjuridiques.txt (Thème : Gestion de l'eau)"},
    {"q": "Quelles sont les exigences de conformité pour les équipements de sécurité ?", "expected": "data/Articles.txt (Normes de sécurité)"},
    {"q": "Quel est le tarif horaire pour une expertise ou un étalonnage métrologique ?", "expected": "data/Termesjuridiques.txt (Décret n° 2001-588 / Expertise)"},
    {"q": "Quelle autorité surveille les établissements de troisième catégorie ?", "expected": "data/Articles.txt (Article 294 / Surveillance administrative)"},
    {"q": "Quelles sont les obligations de l'exploitant d'un dépôt d'explosifs ?", "expected": "data/Termesjuridiques.txt (Sécurité / Matières explosives)"},
    {"q": "Quelle loi régit le contrôle sanitaire vétérinaire à l'exportation ?", "expected": "data/Lois.txt (Contrôle vétérinaire / Article 3)"}
]